### ISSUE TITLE
Missing If/Else-statement at 426 in ColorLCDShield.cpp

### ISSUE THREAD

**Issue by culpinnis** [sparkfun/ColorLCDShield#16]
Hi,

correct me if i am wrong, but I think at line 426 in ColorLCDShield.cpp should be an If/Else-statement to ask if the colors should be swapped. Without this statement all background colors in character printing are swapped even if it is not necessary. 
By commenting out these lines everything is working correctly for me.

Regards
Chris

**Comment by ToniCorinne** [comment]
Sorry for the delay on getting back to you on this! We actually don't have those shields in-house any more, so we can't test the code fixes here. If you would like to submit a pull request with the update however (with code you have verified works), we can get that updated for other users. Thanks!
